# github setting
safe: true
# source: <your pages repo>
# destination: <the build dir>
lsi: false
# pygments: true
markdown: kramdown
kramdown:
  input: GFM

# my setting
author:
  name: ongaeshi
  email: ongaeshi0621@gmail.com
